### ISSUE TITLE
Collaboration offer

### ISSUE THREAD

**Issue by alexeevdv** [adamkewley/klamath#2]
Hey!
We have a set of tools for F1/F2 assets. Would you like to contribute your efforts there? The idea is to have a set of crossplatform tools to be able to extract, modify and then pack back fallout assets. It will be very useful during our engine development and probably to any modders that would like to work with fallout assets in the future.

You can list of our tools here: https://github.com/falltergeist

**Comment by adamkewley** [comment]
Hey @alexeevdv,

Yes, this sounds good. What do you think it would entail?

I've been following Falltergeist for years and I love what you guys are doing. I was initially going to directly contribute to the Falltergeist main game engine project but, when I tried, I realized I was out of my depth: Falltergeist is very large and has a lot of domain knowledge about Fallout 1/2 file assets in it. 

Because of that, I decided to develop this project with a focus on having a clean, low-dependency codebase for reading F1/2 assets, so that I could learn how to parse the file formats etc. For klamath, I'm mostly using [Falltergeist](https://github.com/falltergeist/), [darkfo](https://github.com/darkf/darkfo), and [vault13](https://github.com/pingw33n/vault13) as references when I don't quite understand what the [wiki](https://falloutmods.fandom.com/wiki/Category:Fallout_and_Fallout_2_file_formats) says.

One issue with my dev: I don't get a huge amount of time for this :( I have about ~2/3 active side-projects dragging time away from klamath at the moment, but how's best to integrate this tooling? Into the main codebase? Or as a subproject to the falltergeist project page?

**Comment by alexeevdv** [comment]
Feel free to join our discord chat. We can discuss details there
[![Discord](https://img.shields.io/discord/401990446747877376.svg)](https://discord.gg/jxs6WRq)
